// Generated by scripts/measure-ingredient-tray-bounds.mjs from runtime WebP alpha > 16.
// Geometry only: the shared food image files are never cropped or changed.
import type { IngredientId } from '../campaign'

export const INGREDIENT_VISUAL_BOUNDS = {
  "noodle": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 14,
      "top": 86,
      "width": 486,
      "height": 332
    },
    "center": {
      "x": 258.885,
      "y": 255.779
    }
  },
  "egg": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 52,
      "top": 96,
      "width": 408,
      "height": 319
    },
    "center": {
      "x": 262.844,
      "y": 264.533
    }
  },
  "hot-dog": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 57,
      "top": 97,
      "width": 418,
      "height": 334
    },
    "center": {
      "x": 267.473,
      "y": 261.254
    }
  },
  "sauce": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 38,
      "top": 103,
      "width": 436,
      "height": 313
    },
    "center": {
      "x": 258.14,
      "y": 260.628
    }
  },
  "scallion": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 62,
      "top": 105,
      "width": 388,
      "height": 295
    },
    "center": {
      "x": 256.854,
      "y": 258.581
    }
  },
  "cilantro": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 29,
      "top": 77,
      "width": 452,
      "height": 356
    },
    "center": {
      "x": 259.546,
      "y": 262.502
    }
  },
  "onion": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 36,
      "top": 77,
      "width": 443,
      "height": 359
    },
    "center": {
      "x": 261.377,
      "y": 257.789
    }
  },
  "chili-powder": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 51,
      "top": 112,
      "width": 415,
      "height": 290
    },
    "center": {
      "x": 258.235,
      "y": 265.893
    }
  },
  "turkey-noodle": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 57,
      "top": 108,
      "width": 407,
      "height": 296
    },
    "center": {
      "x": 261.223,
      "y": 261.998
    }
  },
  "cheese": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 39,
      "top": 88,
      "width": 451,
      "height": 338
    },
    "center": {
      "x": 267.369,
      "y": 248.123
    }
  },
  "corn": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 82,
      "top": 127,
      "width": 348,
      "height": 257
    },
    "center": {
      "x": 256.846,
      "y": 258.415
    }
  },
  "orleans": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 15,
      "top": 114,
      "width": 479,
      "height": 296
    },
    "center": {
      "x": 260.79,
      "y": 262.813
    }
  },
  "bacon": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 16,
      "top": 101,
      "width": 490,
      "height": 349
    },
    "center": {
      "x": 258.809,
      "y": 283.84
    }
  },
  "tenderloin": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 21,
      "top": 90,
      "width": 471,
      "height": 336
    },
    "center": {
      "x": 261.928,
      "y": 261.088
    }
  },
  "enoki": {
    "sourceWidth": 512,
    "sourceHeight": 512,
    "bounds": {
      "left": 86,
      "top": 91,
      "width": 345,
      "height": 317
    },
    "center": {
      "x": 259.673,
      "y": 249.977
    }
  }
} satisfies Record<IngredientId, { sourceWidth: number; sourceHeight: number; bounds: { left: number; top: number; width: number; height: number }; center: { x: number; y: number } }>
